version: '3.9'

name: "trainerHub"

volumes: 
  postgres_data_trainer:
  
services:

  postgres:
    image: 'postgres:16.6'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: trainer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_trainer:/var/lib/postgresql/data